# Generated by Django 5.2.6 on 2026-01-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='references',
            new_name='reference',
        ),
    ]
