# Generated by Django 5.2.6 on 2026-01-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_paid_event',
            field=models.BooleanField(default=False, verbose_name='paid event'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_configure_photostrip',
            field=models.PositiveIntegerField(default=120, verbose_name='time configure photostrip'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_download',
            field=models.PositiveIntegerField(default=60, verbose_name='time download'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_payment',
            field=models.PositiveIntegerField(default=60, verbose_name='time payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_take_picture',
            field=models.PositiveIntegerField(default=180, verbose_name='time take picture'),
        ),
    ]
