# Generated by Django 5.2.6 on 2026-01-21 12:09

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_event_is_paid_event_event_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_price_per_print_strip',
            field=models.IntegerField(blank=True, null=True, verbose_name='additional price per print strip'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photobooth.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photobooth voucher',
                'verbose_name_plural': 'photobooth vouchers',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photobooth.voucher'),
        ),
    ]
