# Generated by Django 5.2.6 on 2026-01-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_event_additional_price_per_print_strip_voucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='photobooth/files/'),
        ),
    ]
