# Generated by Django 5.2.6 on 2026-01-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shutter_speed',
            field=models.CharField(default='1/60', max_length=255, verbose_name='shutter speed'),
        ),
    ]
