# Generated by Django 5.2.6 on 2026-01-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0006_alter_event_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_print_strip',
            field=models.IntegerField(default=2, verbose_name='max print strip'),
        ),
    ]
