# Generated by Django 5.2.6 on 2026-01-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0007_event_max_print_strip'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='live_video',
            field=models.FileField(blank=True, null=True, upload_to='photobooth/live/'),
        ),
    ]
