# Generated by Django 5.2.6 on 2026-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0008_file_live_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('photostrip', 'Photostrip'), ('live_video', 'Live Video'), ('gif', 'GIF'), ('default', 'Default')], default='default', max_length=20),
        ),
    ]
