# Generated by Django 5.2.6 on 2026-03-26 03:47

import services.photobooth.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0009_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=services.photobooth.models.file.photobooth_file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='live_video',
            field=models.FileField(blank=True, null=True, upload_to=services.photobooth.models.file.photobooth_file_upload_path),
        ),
    ]
