# Generated by Django 5.2.6 on 2026-03-26 03:58

import services.photobooth.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0010_alter_file_file_alter_file_live_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=services.photobooth.models.file.photobooth_file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='live_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=services.photobooth.models.file.photobooth_file_upload_path),
        ),
    ]
