# Generated by Django 5.2.6 on 2026-03-28 02:11

import services.photobooth.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0011_alter_file_file_alter_file_live_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=services.photobooth.models.file.photobooth_file_upload_path),
        ),
    ]
