# Generated by Django 5.2.6 on 2026-03-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0012_file_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='event',
            name='flash',
        ),
        migrations.RemoveField(
            model_name='event',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shutter_speed',
        ),
    ]
