# Generated by Django 5.2.6 on 2026-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0013_remove_event_aperture_remove_event_flash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=10, verbose_name='orientation'),
        ),
    ]
