# Generated by Django 5.2.6 on 2026-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0016_event_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
