# Generated by Django 5.2.6 on 2026-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0017_event_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
