# Generated by Django 5.2.6 on 2026-04-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0018_event_is_active'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='event',
        ),
        migrations.AddField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
