# Generated by Django 5.2.6 on 2025-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_id',
        ),
        migrations.AlterField(
            model_name='template',
            name='location',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
