# Generated by Django 5.2.6 on 2025-12-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_remove_template_template_id_alter_template_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='location',
            field=models.FileField(upload_to='templates'),
        ),
    ]
