# Generated by Django 5.2.6 on 2026-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_template_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='location',
            field=models.FileField(blank=True, null=True, upload_to='templates'),
        ),
    ]
