# Generated by Django 5.2.6 on 2026-04-22 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_template_location'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='tenant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
