# Generated by Django 5.2.6 on 2025-12-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokentransaction',
            old_name='created_at',
            new_name='created',
        ),
    ]
