# Generated by Django 5.2.6 on 2025-12-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_created_at_tokentransaction_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokentransaction',
            options={'verbose_name': 'token transaction', 'verbose_name_plural': 'token transactions'},
        ),
    ]
