# Generated by Django 5.2.6 on 2025-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_tokentransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentransaction',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
