# Generated by Django 5.2.6 on 2025-12-10 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('transaction', '0006_tokentransaction_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuptransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='product.product'),
        ),
    ]
