# Generated by Django 5.2.6 on 2025-12-10 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('transaction', '0007_remove_topuptransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuptransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='product.product'),
        ),
    ]
