# Generated by Django 5.2.6 on 2025-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_topuptransaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topuptransaction',
            old_name='amount',
            new_name='token',
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
