# Generated by Django 5.2.6 on 2025-12-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_rename_amount_topuptransaction_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='qris',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
