# Generated by Django 5.2.6 on 2025-12-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_topuptransaction_expired_at_topuptransaction_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuptransaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
