# Generated by Django 5.2.6 on 2025-12-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_topuptransaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuptransaction',
            name='qris',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
