# Generated by Django 5.2.6 on 2026-05-10 13:11

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photobooth', '0019_remove_voucher_event_voucher_tenant'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('customer_name', models.CharField(max_length=255, verbose_name='customer name')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='customer phone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('location', models.TextField(blank=True, verbose_name='location')),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('end_at', models.DateTimeField(verbose_name='end at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20, verbose_name='status')),
                ('source', models.CharField(choices=[('manual', 'Manual Input'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='manual', max_length=20, verbose_name='source')),
                ('all_day', models.BooleanField(default=False, verbose_name='all day')),
                ('color', models.CharField(blank=True, help_text='Optional frontend calendar color, example: #3788d8', max_length=20, verbose_name='calendar color')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photobooth_bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Optional existing photobooth event/package.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='photobooth.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_event_bookings', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Photobooth Event Booking',
                'verbose_name_plural': 'Photobooth Event Bookings',
                'ordering': ['start_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'start_at'], name='agenda_agen_tenant__075c99_idx'), models.Index(fields=['tenant', 'end_at'], name='agenda_agen_tenant__8e2495_idx'), models.Index(fields=['tenant', 'status'], name='agenda_agen_tenant__a361ad_idx')],
            },
        ),
    ]
