# Generated by Django 5.2.6 on 2026-05-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('photobooth', '0019_remove_voucher_event_voucher_tenant'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['start_at', '-id'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_photobooth_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional existing photobooth event/package.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='photobooth.event'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photobooth_event_agendas', to='tenant.tenant'),
        ),
    ]
