# Generated by Django 5.2.6 on 2025-12-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
