# Generated by Django 5.2.6 on 2025-09-25 08:06

import core.common.generators
import services.account.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', services.account.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
        migrations.AddField(
            model_name='user',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
    ]
