# Generated by Django 5.2.6 on 2025-12-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
